### ISSUE TITLE
Ablation Study in FCL

### ISSUE THREAD

**Issue by RawFisher** [zhihou7/HOI-CL#11]
Hi! Thank for your excellent work!
I am confusing about the ablation study.
Could you explain every `noise_type` value meaning and which one stand for verb fabricator?(noise_type=0,2,3,8,4,5,7,6)
https://github.com/zhihou7/HOI-CL/blob/b9ed42cbdde9fffe1d436068793db392f9011a79/lib/networks/Fabricator.py#L160-L182

**Comment by zhihou7** [comment]
Sorry for the confusing code. This includes some redundant code. 
To make sure the dimension of Fabricator is unchanged, we add empty (zero variables) variable to the input. However, I think this is the same as removing the empty variable because the optimized does not train the corresponding weights ( those weights are died because of Relu).

I have updated the comments in the code. Some ablation studies are really meaningless and stupid.

**Comment by RawFisher** [comment]
Thanks for your replying!
I have one more question about the verb fabricator. 
What does verb fabricator mean? 
Is it just removing the object identify embedding in fabricated compositional branch or using verb identify embedding, noise and verb to fabricator to generate faked verb?
In the paper
![image](https://user-images.githubusercontent.com/26201819/132944592-2398b649-4475-4109-a762-e0ad0e4dc617.png)
![image](https://user-images.githubusercontent.com/26201819/132944568-64286ee3-e6e3-4aa8-94cd-0ae152f27242.png)
Whether row 4 in table 4 and row 4 in table 19 are the same setting?

**Comment by zhihou7** [comment]
It is using verb identify embedding, noise and verb to fabricator to generate faked verb. Experimentally, this still works a little. We think balancing the data distribution via fabricating features is most important.

No, FCL + verb fabricator is using object and verb fabricator jointly, while verb fabricator we only use verb fabricator. In fact, verb fabricator only still benefit zero-shot setting, while verb fabricator only has limited improvement on long-tailed setting ( the full setting in Table. 19). However, when we use verb fabricator and object fabricator jointly, we did not observe further improvement than object fabricator only （row 4 in Table 4)


Hope this response is helpful.

Regards,

**Comment by RawFisher** [comment]
Thank you very much for your answer! Your answer solves my question!
During reading the code, I have another question about the object identify embedding.
https://github.com/zhihou7/HOI-CL/blob/735c6940b75c504399ece9e801eeb25924f2da21/lib/networks/Fabricator.py#L22-L31
In fabricator, the object identify embedding is randomly initalized and it is `trainable`(line 24).
Does it indicate that object identify embedding would be updated during training? (I am not familiar with tensorflow)
I think object identify embedding is produced offline like one-hot or word embedding and would not be updated during  training. Maybe I misunderstand?

**Comment by zhihou7** [comment]
Yes. It is updated in an end-to-end way during training (I also emphasize this in the paper). It is different from one-hot and word embedding.

**Comment by RawFisher** [comment]
Thank you for answering patiently. Sincere thanks.
