### ISSUE TITLE
HOI-COCO data format 

### ISSUE THREAD

**Issue by daoyuan98** [zhihou7/HOI-CL#16]
Hi, Thank you again for your great work!

In the Trainval_GT_VCOCO_obj_21.pkl, which contains the split of HOI-COCO, for each training sample, the format seems to be 
[image_id, action_list1, human_box, object_box, action_list2, object_list]. 
May I ask what is the difference between action_list1 and action_list2?

**Comment by zhihou7** [comment]
one is for verb classes( i.e., 21 classes), the other one is for HOI classes (i.e., 222 classes) (include verb and object). The number of HOI classes is much larger than the number of verb classes. You can distinguish with that according the value of the number.

**Comment by zhihou7** [comment]
Sorry for getting confusing you. I might provide wrong information to you in the last message. The second row is the verb label and the 4th row is all verb labels of person ( might include interactions with other objects). the last row is object label. 

You can get the composition label as follow:

https://github.com/zhihou7/HOI-CL/blob/735c6940b75c504399ece9e801eeb25924f2da21/lib/ult/ult.py#L642

**Comment by daoyuan98** [comment]
Noted! Thank you so much for your reply!

**Comment by daoyuan98** [comment]
Hi, Sorry to open this issue again. I still have some question about the HOI-COCO dataset.
I just wanted to check, 
(1) Is the results reported in ATL on HOI-COCO considers 21 verb classes and the train file is Trainval_GT_VCOCO_obj_21.pkl?
(2) Which test set did you use? I found only 8537 images in that file, which is different from 10346 reported in paper.

Sincerely hope you can help!

**Comment by zhihou7** [comment]
Sorry for getting you latter, 
1), Yes, it is Trainval_GT_VCOCO_obj_21.pkl.
2), The test set is from this file: "Test_Faster_RCNN_R-50-PFN_2x_HICO_DET.pkl" in https://cloudstor.aarnet.edu.au/plus/s/9YxboaI6d5lITLk.

Sorry for getting confusing you. The numbers of images reported in paper is directly copied from iCAN. And those files are also followed from the released pkls in iCAN. I did not check the images, and I think  it is better to refer to the two files: Trainval_GT_VCOCO_obj_21.pkl and Test_Faster_RCNN_R-50-PFN_2x_HICO_DET.pkl.

**Comment by daoyuan98** [comment]
Thank you so much for your reply!
I am sorry to have to bother you again.. It seems Test_Faster_RCNN_R-50-PFN_2x_HICO_DET.pkl has only detection annotation (not hoi detection results). Besides, it has 9658 images (with id from 1 - 9767), but I didn't find how these id correlates with that of VCOCO.. Did I miss any files? 

Thanks again for your reply!

**Comment by zhihou7** [comment]
"lib/ult/vsrl_eval2.py" includes the evaluation process.

    def get_vcoco2():
        from ult.vsrl_eval2 import VCOCOeval
        vcocoeval = VCOCOeval(cfg.DATA_DIR + '/' + 'v-coco/data/vcoco/vcoco_test.json',
                          cfg.DATA_DIR + '/' + 'v-coco/data/instances_vcoco_all_2014.json',
                          cfg.DATA_DIR + '/' + 'v-coco/data/splits/vcoco_test.ids')
        return vcocoeval

Those files are generated after you have installed v-coco dataset.

**Comment by daoyuan98** [comment]
Thanks! 
So from my understanding, HOI-COCO actually takes the same test set with VCOCO, but with different number of actions (21), and split (rare, non-rare)?

**Comment by zhihou7** [comment]
Yes!

**Comment by daoyuan98** [comment]
Thank you so much!
