### ISSUE TITLE
zero-shot setting

### ISSUE THREAD

**Issue by liuc-v** [zhihou7/HOI-CL#28]
Hi, thanks for you work! 
In the zero-shot setting, for an unknown Human-Object Interaction (HOI), the approach is to either remove the corresponding HOI label (including object, person, and action) or to keep the bounding boxes and labels for objects and persons known, but assign the action as unknown.

**Comment by zhihou7** [comment]
Hi, I did not get your questions. which zero-shot setting that you are confusing?

**Comment by liuc-v** [comment]
Thanks for your reply！One approach is to remove all annotations related to the unseen HOI group in one image. This includes the bounding boxes (bbox), object labels, and action labels associated with the unseen HOI group. Another approach is to only mask the action labels while preserving the bounding boxes and object labels associated with the unseen HOI group. This means that the annotation information for the objects, such as their recognized categories and positions, is retained, but the specific interaction actions between objects and humans are uncertain. I am not sure which approach do you use.
