### ISSUE TITLE
Model used in affordance feature extraction

### ISSUE THREAD

**Issue by FeiX-OvO** [zhihou7/HOI-CL#5]
Hi, 

I'm experimenting on the affordance features from ATL. I see there are pretrained networks posted, but in feature extraction script, it's using model names like 'ATL_union_batch1_semi_l2_def4_vloss2_rew2_aug5_3_x5new_coco_res101'. I'm wondering if this is provided somewhere or I have to generate on my own?

Thanks in advance!

**Comment by zhihou7** [comment]
You can train the ATL model by yourself, which requires around 3 GPU days. We also provide the pre-trained model in [MODEL.md](https://github.com/zhihou7/HOI-CL/blob/master/MODEL.md).

The previous might be confusing. We have updated MODEL.md


    ATL model (HICO-DET): https://cloudstor.aarnet.edu.au/plus/s/NfKOuJKV5bUWiIA
    
    This is the ATL pre-trained model on HICO-DET. This model is fine-tuned with around 500000 iterations after we train ATL model. We pick the best checkpoint on HOI detection. Noticeably, the fine-tuning step does not improve the result of affordance recognition apparently. The model name is ATL_union_batch1_atl_l2_def4_epoch2_epic2_cosine5_s0_7_vloss2_rew2_aug5_3_x5new_coco_res101.
    
    VCL on HICO: https://drive.google.com/file/d/16unS3joUleoYlweX0iFxlU2cxG8csTQf/view?usp=sharing
    
    model name is VCL_union_multi_ml5_def1_l2_rew2_aug5_3_x5new
    
    VCL on HICO(Res101): https://drive.google.com/file/d/1iiCywBR0gn6n5tPzOvOSmZw_abOmgg53/view?usp=sharing
    
    model name is iCAN_R_union_multi_ml5_def1_l2_rew2_aug5_3_x5new_res101. Here ``iCAN_R'' has no special meaning, just because the code is based on the repository of iCAN.

Both VCL and ATL model can be used for affordance recognition. 

If you have any further questions, feel free to contact me.

**Comment by zhihou7** [comment]
Here is the baseline model on HICO-DET: https://cloudstor.aarnet.edu.au/plus/s/yPiGxk6OZgyP2z3

**Comment by FeiX-OvO** [comment]
That is very helpful, thank you so much!
